# Generated by Django 4.1.6 on 2023-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя стримера')),
                ('photo', models.ImageField(upload_to='photostream/', verbose_name='Фото')),
                ('urltwitch', models.URLField(verbose_name='Ссылка на твич')),
            ],
            options={
                'verbose_name': 'Все стримеры',
                'verbose_name_plural': 'Все стримеры',
            },
        ),
    ]
