# Generated by Django 4.1.6 on 2023-02-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_addproduct_shop'),
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstreamers',
            name='shop',
        ),
        migrations.AddField(
            model_name='allstreamers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.addproduct'),
        ),
    ]
