# Generated by Django 4.1.6 on 2023-02-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0002_remove_allstreamers_shop_allstreamers_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstreamers',
            name='product',
        ),
    ]
