# Generated by Django 4.1 on 2023-01-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='strim_image/', verbose_name='Фото стримера')),
                ('url_twitch', models.URLField(verbose_name='Ссылка на twitch')),
                ('shop', models.BooleanField(default=False, verbose_name='Наличие магазина')),
            ],
        ),
        migrations.CreateModel(
            name='HisStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(null=True, verbose_name='Очки стримеров')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Name_strimers', to='streamers.allstreamers', verbose_name='Имя')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Photo_strimers', to='streamers.allstreamers', verbose_name='Фото стримера')),
                ('url_twitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Url_strimers', to='streamers.allstreamers', verbose_name='Ссылка на twitch')),
            ],
        ),
    ]
