# Generated by Django 4.1 on 2023-01-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisstreamers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='hisstreamers',
            name='photo',
            field=models.ImageField(upload_to='strim_image/', verbose_name='Фото стримера'),
        ),
        migrations.AlterField(
            model_name='hisstreamers',
            name='url_twitch',
            field=models.URLField(verbose_name='Ссылка на twitch'),
        ),
    ]
