# Generated by Django 4.1 on 2023-01-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkusers', '0001_initial'),
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstreamers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lkusers.contribusers'),
        ),
    ]
