# Generated by Django 4.1 on 2023-01-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstreamers',
            options={'verbose_name': 'Все стримеры'},
        ),
    ]
