# Generated by Django 4.1.6 on 2023-02-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstreamers',
            options={'permissions': (('shop.add_AddProduct', 'add product'), ('shop.change_AddProduct', 'change product'), ('shop.delete_AddProduct', 'delete product'), ('shop.view_AddProduct', 'view product')), 'verbose_name': 'Все стримеры', 'verbose_name_plural': 'Все стримеры'},
        ),
    ]
