# Generated by Django 4.1 on 2023-02-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkusers', '0003_remove_hisstreamers_photouser_contribusers_photouser'),
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstreamers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lkusers.contribusers'),
        ),
    ]
