<<<<<<< Updated upstream
# Generated by Django 4.1 on 2023-01-31 20:47
=======
# Generated by Django 4.1 on 2023-02-01 08:06
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи',
<<<<<<< Updated upstream
=======
                'verbose_name_plural': 'Пользователи',
>>>>>>> Stashed changes
            },
        ),
        migrations.CreateModel(
            name='HisStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('points', models.IntegerField(blank=True, verbose_name='Очки за блогера')),
=======
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Очки за блогера')),
>>>>>>> Stashed changes
                ('urltwitch', models.URLField(verbose_name='Ссылка на стримера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkusers.contribusers')),
            ],
            options={
                'verbose_name': 'Стримеры пользователя',
<<<<<<< Updated upstream
=======
                'verbose_name_plural': 'Стримеры пользователей',
>>>>>>> Stashed changes
            },
        ),
    ]
