# Generated by Django 4.1 on 2023-02-01 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photouser', models.ImageField(blank=True, null=True, upload_to='photousers/', verbose_name='Фото пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='HisStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Очки за блогера')),
                ('urltwitch', models.URLField(verbose_name='Ссылка на стримера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkusers.contribusers')),
            ],
            options={
                'verbose_name': 'Стримеры пользователя',
                'verbose_name_plural': 'Стримеры пользователей',
            },
        ),
    ]
