# Generated by Django 4.1 on 2023-01-30 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hisstreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='streamers_photo/', verbose_name='Фото')),
                ('points', models.IntegerField(blank=True, verbose_name='Очки за блогера')),
            ],
            options={
                'verbose_name': 'Стримеры пользователя',
            },
        ),
        migrations.CreateModel(
            name='ContribUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkusers.hisstreamers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
    ]
