# Generated by Django 4.1 on 2023-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribusers',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='hisstreamers',
            options={'verbose_name': 'Стримеры пользователя'},
        ),
        migrations.AddField(
            model_name='hisstreamers',
            name='urltwitch',
            field=models.URLField(default='https://www.twitch.tv/', verbose_name='Ссылка на стримера'),
            preserve_default=False,
        ),
    ]
