# Generated by Django 4.2.1 on 2023-05-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribusers',
            old_name='referal',
            new_name='ref',
        ),
    ]
