# Generated by Django 4.1.6 on 2023-02-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namestreamers', models.CharField(blank=True, help_text='Не требует заполнения', max_length=200, null=True, verbose_name='Имя стримера')),
            ],
            options={
                'verbose_name': 'Магазин стримера',
                'verbose_name_plural': 'МАгазин стримера',
            },
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('photoproduct', models.ImageField(help_text='фото товара', upload_to='photoproduct/', verbose_name='Фото товара')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopstreamers')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
