# Generated by Django 4.1.6 on 2023-02-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='shop',
        ),
    ]
