# Generated by Django 4.1.6 on 2023-02-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_addproduct_shop'),
        ('streamers', '0002_remove_allstreamers_shop_allstreamers_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopStreamers',
        ),
    ]
