# Generated by Django 4.1.6 on 2023-02-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0003_remove_allstreamers_product'),
        ('shop', '0003_delete_shopstreamers'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streamers.allstreamers'),
        ),
    ]
