# Generated by Django 4.1 on 2023-01-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namestreamers', models.CharField(help_text='Введите имя блогера', max_length=200, verbose_name='Имя стримера')),
                ('name', models.CharField(help_text='Наименование товара', max_length=200, verbose_name='Товар')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('photoproduct', models.ImageField(help_text='фото товара', upload_to='photoproduct/', verbose_name='Фото товара')),
                ('photostreamers', models.ImageField(help_text='Фото стримера', upload_to='photostreamers/', verbose_name='Фото блогера')),
            ],
            options={
                'verbose_name': 'Магазин стримера',
            },
        ),
    ]
