# Generated by Django 4.1 on 2023-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStreamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='Цена товара')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('photo', models.ImageField(upload_to='shop_image/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Магазин Стримера',
                'verbose_name_plural': 'Магазины стримеров',
            },
        ),
    ]
