# Generated by Django 4.2.1 on 2023-05-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('photoproduct', models.ImageField(help_text='фото товара', upload_to='photoproduct/', verbose_name='Фото товара')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('published', models.BooleanField(default=1, verbose_name='Удалить товар')),
                ('streamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streamers.allstreamers')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
