# Generated by Django 4.1 on 2023-01-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstreamers',
            name='photostreamers',
        ),
        migrations.AlterField(
            model_name='shopstreamers',
            name='namestreamers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streamers.allstreamers'),
        ),
    ]
