# Generated by Django 4.1 on 2023-01-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shopstreamers_photostreamers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=200, verbose_name='Товар')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('photoproduct', models.ImageField(upload_to='photoproduct/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Добавить товар',
            },
        ),
        migrations.RemoveField(
            model_name='shopstreamers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopstreamers',
            name='photoproduct',
        ),
        migrations.RemoveField(
            model_name='shopstreamers',
            name='price',
        ),
        migrations.AddField(
            model_name='shopstreamers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.addproduct'),
        ),
    ]
