# Generated by Django 4.1 on 2023-01-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_addproduct_remove_shopstreamers_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstreamers',
            name='product',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopstreamers'),
        ),
    ]
