# Generated by Django 4.1 on 2023-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopstreamers_product_addproduct_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='photoproduct',
            field=models.ImageField(upload_to='static/img', verbose_name='Фото товара'),
        ),
    ]
