# Generated by Django 4.1 on 2023-01-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisstreamers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hisstreamers',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hisstreamers',
            name='url_twitch',
        ),
        migrations.DeleteModel(
            name='ShopStreamer',
        ),
        migrations.RemoveField(
            model_name='usersbase',
            name='points',
        ),
        migrations.DeleteModel(
            name='AllStreamers',
        ),
        migrations.DeleteModel(
            name='HisStreamers',
        ),
        migrations.DeleteModel(
            name='UsersBase',
        ),
    ]
