# Generated by Django 4.1.6 on 2023-02-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
